[book]
title = "Rust开发一个玩具语言"
authors = []
description = "Rust开发一个玩具语言"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/awesome-kusion/rust-toy-lang-book"
edit-url-template = "https://github.com/awesome-kusion/rust-toy-lang-book/edit/main/{path}"
git-repository-icon = "fa-github"
